---
- name: block IP address
  hosts: checkpoint
  become: true
  tasks:
    - name: Install ufw package
      apt:
        name: ufw
        state: present

    - name: Add firewall
      ufw:
        rule: deny
        from: 192.168.0.10

    - name: Enable UFW Firewall
      service:
        name: ufw
        state: restarted
        enabled: yes
